version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver
    ports:
      - "8000:8000"
    # EXPOSE 8000
    volumes:
      - .:/djangosoko

    # CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

