# Generated by Django 4.1.5 on 2023-01-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sokoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Soko', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='Software Engineer', max_length=255),
        ),
    ]
