# Generated by Django 4.1.5 on 2023-01-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sokoapp", "0002_alter_artisan_country_alter_employee_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisan",
            name="marital_status",
            field=models.CharField(
                choices=[("Single", "Single"), ("Married", "Married")],
                default="S",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="artisan",
            name="religion",
            field=models.CharField(
                choices=[("Christian", "Christian"), ("Muslim", "Muslim")],
                default="C",
                max_length=20,
            ),
        ),
    ]
